### PR TITLE
More readable and improved NTTs for NTRU

### PR DESCRIPTION
**Pull request by vincentvbh**
More NTT results.
NTT-based polymul cycles:
ntruhps2048509: 103k (24 MHz), 105k (168 MHz)
ntruhps2048677: 148k (24 MHz), 150k (168 MHz)
ntruhrss701: 148k (24 MHz), 150k (168 MHz)
ntruhps4096821: 181k (24 MHz), 185 (168 MHz)
The transformations will be detailed in the future.

### CODE REVIEW

**Comment by mkannwischer** [comment]
Thanks @vincentvbh.
These are the numbers that I am getting: 

| scheme | implementation | key generation [cycles] | encapsulation [cycles] | decapsulation [cycles] |
| ------ | -------------- | ----------------------- | ---------------------- | ---------------------- |
| ntruhps2048509 (100 executions) | m4f | AVG: 2,867,040 <br /> MIN: 2,867,035 <br /> MAX: 2,867,072 | AVG: 565,341 <br /> MIN: 565,340 <br /> MAX: 565,374 | AVG: 538,297 <br /> MIN: 538,296 <br /> MAX: 538,330 |
| ntruhps2048677 (100 executions) | m4f | AVG: 4,599,942 <br /> MIN: 4,599,933 <br /> MAX: 4,599,968 | AVG: 811,676 <br /> MIN: 811,675 <br /> MAX: 811,708 | AVG: 804,287 <br /> MIN: 804,286 <br /> MAX: 804,319 |
| ntruhps4096821 (100 executions) | m4f | AVG: 6,067,154 <br /> MIN: 6,067,143 <br /> MAX: 6,067,179 | AVG: 1,010,199 <br /> MIN: 1,010,198 <br /> MAX: 1,010,232 | AVG: 1,013,226 <br /> MIN: 1,013,224 <br /> MAX: 1,013,258 |
| ntruhrss701 (100 executions) | m4f | AVG: 4,210,467 <br /> MIN: 4,210,459 <br /> MAX: 4,210,494 | AVG: 368,351 <br /> MIN: 368,351 <br /> MAX: 368,385 | AVG: 860,213 <br /> MIN: 860,212 <br /> MAX: 860,246 |

It compares to the previous ones:

| scheme | implementation | key generation [cycles] | encapsulation [cycles] | decapsulation [cycles] |
| ------ | -------------- | ----------------------- | ---------------------- | ---------------------- |
| ntruhps2048509 (100 executions) | m4f | AVG: 2,861,243 <br /> MIN: 2,861,238 <br /> MAX: 2,861,274 | AVG: 563,397 <br /> MIN: 563,396 <br /> MAX: 563,429 | AVG: 536,377 <br /> MIN: 536,376 <br /> MAX: 536,410 |
| ntruhps2048677 (100 executions) | m4f | AVG: 4,625,197 <br /> MIN: 4,625,191 <br /> MAX: 4,625,225 | AVG: 820,052 <br /> MIN: 820,052 <br /> MAX: 820,052 | AVG: 812,613 <br /> MIN: 812,607 <br /> MAX: 812,641 |
| ntruhps4096821 (100 executions) | m4f | AVG: 6,116,170 <br /> MIN: 6,116,159 <br /> MAX: 6,116,195 | AVG: 1,027,339 <br /> MIN: 1,027,337 <br /> MAX: 1,027,371 | AVG: 1,031,143 <br /> MIN: 1,031,141 <br /> MAX: 1,031,176 |
| ntruhrss701 (100 executions) | m4f | AVG: 4,233,603 <br /> MIN: 4,233,595 <br /> MAX: 4,233,630 | AVG: 375,948 <br /> MIN: 375,947 <br /> MAX: 375,981 | AVG: 867,921 <br /> MIN: 867,920 <br /> MAX: 867,954 |

This seems like a very small speed-up for `ntruhps2048509` and a slow down for the other parameter sets. 
What numbers have you been getting?

**Comment by vincentvbh** [comment]
I think it is a slow down for `ntruhps2048509` due to a more flexible base multiplication, and small speed-up for other parameter sets.

**Comment by mkannwischer** [comment]
Indeed. The other way round. Sorry. 
Is there any benefit of the base mul of ntruhps2048509?

**Comment by vincentvbh** [comment]
It supports a more flexible computation with NTTs.
Originally, the entire assembly code supports `polymul` only. 
But now it supports separate calls for NTT, base mul, and iNTT. So one can perform something like A * B, C * B with three NTTs. I don't think this is presented in the current NTRU code, but you can use the code to do more things as long as you know what you are doing.

**Comment by mkannwischer** [comment]
LGMT. Sorry for not merging this earlier.

**Pull request merged**
