### PR TITLE
Multiplatform support

### PR DESCRIPTION
**Pull request by rpls**
This PR will add support for multiple platforms, similar to how PQM3 does.

- [x] Adapt the PQM3 build system
- [x] Add support for the discovery board
- [x] Add support for the Nucleo-L476G
- [x] Add support for the CW308-F3 board
- [ ] ~~Add support for the Nucleo-L4R5ZI~~
- [x] Add support for some non-STM32 platform.
- [x] Adapt the python scripts to use the new build system
- [x] Adapt the evaluation scripts to support multiple platforms
- [x] Write README.md

Depends on the PR mupq/mupq#57 of the `mupq` repo

### CODE REVIEW

**Comment by rpls** [comment]
Adapting the new build system will take some work in the `mupq` repo as well. The new build system is able to build a library per scheme implementation, so the mupq python script doesn't need to bother with it for the size benchmarks. Also I'll abstract the `Platform` Class a bit more. Right now, the only the `run` method is used anyway, so I'll make this an abstract method and the platform interface will have to bother with "Run binary X on platform and get output".

**Comment by rpls** [comment]
@Ko- and @mkannwischer you can start reviewing this. The stm32f4discovery platform should work as expected.

**Comment by mkannwischer** [comment]
Thanks, @rpls!
Looks good to me and works nicely for me on the F407. 
You may want to rebase on top of #173.

**Comment by rpls** [comment]
@mkannwischer Please retest. You may also want to test the new QEMU platform mps2-an386 (works with QEMU>=5.2). This simulates a board with 4MB Flash and 4MB RAM... which allowed me to stack benchmark nearly all schemes (only exceptions are `rainbowV*` and `mceliece{4,6,8}*`). I added a new HAL function that queries the maximum size of the stack. The old stack test made an assumption about the max size, so we needed an abstraction here anyway.

Apart from this, I moved all reusable code & buildsystem to the `mupq` repository, so we can reuse for `pq{m4,riscv}`.

I'm reasonably happy with this now. Only thing missing for now is the test vector stuff and a readme for the Makefile magic.

**Comment by rpls** [comment]
As far as I'm concerned, this is ready now. I'm skipping the L4R5ZI platform for now, since it's not supported by opencm3 yet (all the important stm32l4 libraries should work, they match the chips reference documentation, but there's no linker script yet). I now made the "all-in-one" compilation approach the default. I also added a documentation of the build system in mupq, and adapted the `README.md` here. This should still be validated on a MacOS platform.

**Comment by rpls** [comment]
Everything is up to date and I also posted benchmarks now.

**Comment by mkannwischer** [comment]
Thanks @rpls for all the work.
This looks good to me now!

**Pull request merged**
