### PR TITLE
Remove schemes that are no longer under consideration by NIST

### PR DESCRIPTION
**Pull request by mkannwischer**
The goal of pqm4 was always to evaluate NIST PQC candidates and I believe we should keep it like that. 
My plan is to keep the best implementations of winners and the round-4 candidates and add any suitable candidates submitted the signature on-ramp.
PQClean is probably going down the same path. I've opened a PR there, too: https://github.com/PQClean/PQClean/pull/448. 

I've created a tag for the current code: https://github.com/mupq/pqm4/releases/tag/Round3. 

Are there any objections or opinions?

I've also benchmarked everything with the most recent Arm toolchain (arm-none-eabi-gcc (Arm GNU Toolchain 11.3.Rel1) 11.3.1 20220712 from https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads).

### CODE REVIEW

**Comment by rpls** [comment]
Should we create an archive for the old schemes? Or is the git-history archive enough? Or mutiple folders such as `archive` (rejected), `candidates` (currently under consideration), `finalized` (picked)? The build-system should alread support this without a problem.

**Comment by mkannwischer** [comment]
I removed SIKE, too. 
See https://eprint.iacr.org/2022/975 and https://csrc.nist.gov/csrc/media/Projects/post-quantum-cryptography/documents/round-4/submissions/sike-team-note-insecure.pdf

**Comment by mkannwischer** [comment]
Finally got around to run the benchmarks with the most recent Arm toolchain (`arm-none-eabi-gcc (Arm GNU Toolchain 11.3.Rel1) 11.3.1 20220712` from https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads)

**Comment by mkannwischer** [comment]
@rpls, can we merge this?

**Comment by mkannwischer** [comment]
I rebased on top of #244.

**Pull request merged**
