### PR TITLE
Constant-time AES (https://eprint.iacr.org/2020/1123)

### PR DESCRIPTION
**Pull request by mkannwischer**
On the pqcforum, Daniel Bernstein pointed put that pqm4's current t-table AES implementation potentially introduces timing leakage to implementations using AES with secret inputs on Cortex-M4 platforms that have a data cache. While we were aware of that for quite some time, there simply wasn't a good open-source implementation available that implements both AES128 and AES256 including the key schedules without using LUTs. 

A recent [paper](https://eprint.iacr.org/2020/1123) accepted to [TCHES2021/1](https://tches.iacr.org/index.php/TCHES/issue/view/193) by Alexandre Adomnicai and Thomas Peyrin describes exactly that and has [code](https://github.com/aadomn/aes) available. I have integrated the "fully-fixsliced" implementations into pqm4 and fixed [some bugs](https://github.com/aadomn/aes/pull/1).
Unfortunately, this does introduce some slowdown (these are my own benchmarks in the pqm4 setup): 

| type       | implementation                                             | AES-128 | AES-256 | 
|-----------  | --------------------------------------------------------------------------------------------------------------------------- | -------------- | -------------- | 
| t-table    | [[SS16]](https://eprint.iacr.org/2016/714.pdf),  [code](https://github.com/Ko-/aes-armcortexm) | 41 cc/byte  | 56 cc/byte |
| fixsliced | [[AP21]](https://eprint.iacr.org/2020/1123), [code](https://github.com/aadomn/aes)                   | 85 cc/byte  | 117 cc/byte |

As the new implementation processes two blocks in parallel, there is an additional penalty if an odd number of blocks is processed. 

As far as I know, there are 4 schemes in PQM4/PQClean at the moment that use AES: FrodoKEM, NTRUPrime (ntrulpr), Kyber (kyber-90s), and HQC. For FrodoKEM, this change is particularly annoying as the inputs processed are public anyway and, hence, one does not care about leaking it. Similarly, some of the AES calls in NTRUPrime and Kyber only process public data. 
Therefore, I propose to additionally ship the previous t-table implementation but attach the `_publicinputs` to the function names. 
I've made the according to changes to the implementations of NTRUPrime, Kyber, and NTRUPrime in pqm4. For implementations coming from PQClean this is currently not possible, so those default to the new constant-time implementation. This may be possible in the future (https://github.com/PQClean/PQClean/issues/336), but I don't this is a priority right now. 

Before I merge this, I would like to hear some opinions about this approach and its implementation.

### CODE REVIEW

**Comment by Ko-** [comment]
Hi. Cool that you took the time to make these changes. I think that shipping both AES implementations and calling one of them `_leaktime` is a nice solution, although it it weird that a `clean` implementation that uses AES with public data is now 'punished' more than a `ref`/`opt` implementation would be, simply because there's no way to indicate which AES to pick from PQClean. Shouldn't that be addressed first?
Furthermore, I'm not a fan of completely removing a shared AES API from `mupq/common`. Wouldn't it be nicer to have what we had as a default in `mupq/common` but then allow overrides for the struct definitions by adding something like `#ifndef MUPQ_AESCTX`?

**Comment by thomwiggers** [comment]
>  Furthermore, I'm not a fan of completely removing a shared AES API from mupq/common. Wouldn't it be nicer to have what we had as a default in mupq/common but then allow overrides for the struct definitions by adding something like #ifndef MUPQ_AESCTX?

Could we not just override `aes.h` by including it in `pqm4` and specifying `pqm4`'s `common` dir earlier on the include paths (`-I`)?

**Comment by mkannwischer** [comment]
Thanks, @Ko-. Feel free to integrate this into PQClean. I won't get to it very soon, and there seems to be very little interest to get it into PQClean.
Thanks, @thomwiggers, that should work, I'll implement that. 

It has been pointed out to me that we could change `_leaktime` to `_publicinputs` to be consistent with SUPERCOP (https://bench.cr.yp.to/tips.html). I actually think `_publicinputs` is a better name for it, so I will change it.

**Comment by mkannwischer** [comment]
Finally found the time to get this done. Thank you.

**Pull request merged**
