### PR TITLE
Cortex-M4 Optimizations for {R,M}LWE Schemes

### PR DESCRIPTION
**Pull request by alperbilgin**
This pull request contains the code described in the paper [Cortex-M4 Optimizations for {R,M}LWE Schemes](https://eprint.iacr.org/2020/012) for all parameter sets of Kyber.  The source codes can also be found on https://github.com/erdemalkim/NewHope-Compact-M4.

Note that there is a small speed difference between this commit and the numbers in Table 4 of the paper due to the link-time optimization ('-flto'). pqm4 does not enable link-time optimizations while all codes described in [Cortex-M4 Optimizations for {R,M}LWE Schemes](https://eprint.iacr.org/2020/012) enable it.

### CODE REVIEW

**Comment by Ko-** [comment]
Hi, thanks for creating that PR!

Before we can benchmark and merge it, I think there might still be a small bug somewhere. The test vectors that `pqm4` generates for this implementation don't match with the test vectors that it generates for the `clean` implementation.

For example, for your implementation of `kyber768-90s`, I get these values:
```
934d60b35624d740b30a7f227af2ae7c678e4e04e13c5f509eade2b79aea77e2
3e2a2ea6c9c476fc4937b013c993a793d6c0ab9960695ba838f649da539ca3d0
736245f1f54e7cdb681427aa92d8aa7023c066f1b0da1347c3495e3d06a919ca185f443d2830cc29e0486e17a45a2a0175c5580ff82ecd189a3e6aa99f036235d707732ac9594c7049f33c2099055858880b08c6203936ec2c52629518c34570dbd6bd1f79729b3251e5f64362ca0ebc2b1a2847803fc912ed679157d51771d618f9123fa9106fa5a48f6fab94a26579fa1906ec60cd9b608b5415545cf891029484bf26bf76c24c5a160224dbcc84851932b15cac4c4752906ceab861e76bb806780b6cb31189083115b9c9f073bf61696683094bebc57b786c464f21006037cf3c6635dc81440ce707aeba61751c667aea0f76838dd713bc8c137cdc2700b7f8253d592c9c593fa1f2af14d22af9c8395eba048a6ca8980765c214c731d1c6d9eb734b24b8f6cb577fcb9e4be848e617d064c875b1e83b31220083fa6a2f983ce7e0b14b69417d72486d6b2cb9c87c570bc87c635adc544cd39ca4e6007d1d761bbf92257c975f9923a2d10680470acf03b59612dc7143d449cc9ca6c92a962b8b90fc87543f786a0024cd6a31c715535a72022193016e22bb58144435965154c97004b9a9bc4486970c6baf4b633312b74b4170b6306566d4e73fa6435e7a791813154902caa6a10b6e255c7299445e42176cee9b5fb3a0b6d0f7198fc4479509c10ec4cf30b2b02ec0371a691428aa6562fa35be07c5ca98b06cc028e0b4417337cc6ed86d724a5a537700efb17eb575c101552fede11dbc35c772855cb43b1ad199b9af815b17859ea6cc620e72b496994159463496a4b5b5750f332334bf84c6f49b30df146ac1e6a3b9c96ef9883ab2dc2fae502ba045026160ac67998ab9225bf6b428f554a0f6a65158888082d7bf1f90b4c6b54867fc682d6a395bea81eecc985db14cbb4834d0b7c0b414647d2a63a3f0636930c8b300c4161617e21019a26973cbc48196938433911ce0f72928524a9b0758645945c043151ba9365cd0334c349df3566dfa3371a5f7a61bc0b789254fe3b276260a8d001a88947a643e92cae264271a961fa9420894aca828b99bd9bcb7fb43093207ccc1c12a31768430528f5ad6a1f194ca8d09b3a7615adefc18ab56b841d39b94c31680f8292d89515feb83ef26a8f274cea1fc5309764ce3911c31a08f6739700e39a50b8037df099fb1b94291172417d99f1f497b91f8a20d9583324a21f9a8b7ee7c324362897b464783645a8f970b1117a7eb275022e36bf37b072b828d36048654f3bcd8998bd4f29255133a2e75b523e689676487ce8437c033984c530a1c7114fc264d9ee74f845a10b00bc7c0d88231b77135e0c9f3a79912b0ca8efa1ffd79afa623534cd65e5a1c690630b80ef12f40822549414be6b2c7e14a1db1ab80d095caa981c5736195e1b59e3a07647c307af11b61e4c6557528894dea39f4bc698b7a6b5c4250c78a13d309c7ccc5c0c37c483f2b4fb8475e33d499b9a59a6651268eb3bd64f3b410739a7d834ad6e2384f7003473186799454abd5267eb1471b8c0210f5c92615aeefaa76ace5aae757c9d137454a45038b72bdb2508325c878cda91a11427176b10d74601a67b529386c5e1f2cb42c9537d22864d2e92717ec7a5f7f5c2504f59871b3e7da307fe5e3e4123fb2896e20c45ddaf9cdc54a592f8d
```

For the `clean` implementation, it's this:
```
934d60b35624d740b30a7f227af2ae7c678e4e04e13c5f509eade2b79aea77e2
3e2a2ea6c9c476fc4937b013c993a793d6c0ab9960695ba838f649da539ca3d0
736245f1f54e7cdb681427aa92d8aa7023c066f1b0da1347c3495e3d06a919ca185f443d2830cc29e0486e17a45a2a0175c5580ff82ecd189a3e6aa99f036235d707732ac9594c7049f33c2099055858880b08c6203936ec2c52629518c34570dbd6bd1f79729b3251e5f64362ca0ebc2b1a2847803fc912ed679157d51771d618f9123fa9106fa5a48f6fab94a26579fa1906ec60cd9b608b5415545cf891029484bf26bf76c24c5a160224dbcc84851932b15cac4c4752906ceab861e76bb806780b6cb31189083115b9c9f073bf61696683094bebc57b786c464f21006037cf3c6635dc81440ce707aeba61751c667aea0f76838dd713bc8c137cdc2700b7f8253d592c9c593fa1f2af14d22af9c8395eba048a6ca8980765c214c731d1c6d9eb734b24b8f6cb577fcb9e4be848e6070064c875b1e83b31220083fa6a2f983ce7e0b14b69417d72486d6b2cb9c87c570bc87c635adc544cd39ca4e6007d1d761bbf92257c975f9923a2d10680470acf03b59612dc7143d449cc9ca6c92a962b8b90fc87543f786a0024cd6a31c715535a72022193016e22bb58144435965154c97004b9a9bc4486970c6baf4b633312b74b4170b6306566d4e73fa6435e7a791813154902caa6a10b6e255c7299445e42176cee9b5fb3a0b6d0f7198fc4479509c10ec4cf30b2b02ec0371a691428aa6562fa35be07c5ca98b06cc028e0b4417337cc6ed86d724a5a537700efb17eb575c101552fede11dbc35c772855cb43b1ad199b9af815b17859ea6cc620e72b496994159463496a4b5b5750f332334bf84c6f49b30df146ac1e6a3b9c96ef9883ab2dc2fae502ba045026160ac67998ab9225bf6b428f554a0f6a65158888082d7bf1f90b4c6b54867fc682d6a395bea81eecc985db14cbb4834d0b7c0b414647d2a63a3f0636930c8b300c4161617e21019a26973cbc48196938433911ce0f72928524a9b0758645945c043151ba9365cd0334c349df3566dfa3371a5f7a61bc0b789254fe3b276260a8d001a88947a643e92cae264271a961fa9420894aca828b99bd9bcb7fb43093207ccc1c12a31768430528f5ad6a1f194ca8d09b3a7615adefc18ab56b841d39b94c31680f8292d89515feb83ef26a8f274cea1fc5309764ce3911c31a08f6739700e39a50b8037df099fb1b94291172417d99f1f497b91f8a20d9583324a21f9a8b7ee7c324362897b464783645a8f970b1117a7eb275022e36bf37b072b828d36048654f3bcd8998bd4f29255133a2e75b523e689676487ce8437c033984c530a1c7114fc264d9ee74f845a10b00bc7c0d88231b77135e0c9f3a79912b0ca8efa1ffd79afa623534cd65e5a1c690630b80ef12f40822549414be6b2c7e14a1db1ab80d095caa981c5736195e1b59e3a07647c307af11b61e4c6557528894dea39f4bc698b7a6b5c4250c78a13d309c7ccc5c0c37c483f2b4fb8475e33d499b9a59a6651268eb3bd64f3b410739a7d834ad6e2384f7003473186799454abd5267eb1471b8c0210f5c92615aeefaa76ace5aae757c9d137454a45038b72bdb2508325c878cda91a11427176b10d74601a67b529386c5e1f2cb42c9537d22864d2e92717ec7a5f7f5c2504f59871b3e7da307fe5e3e4123fb2896e20c45ddaf9cdc54a592f8d
```
The first two lines are the public and private key generated by `crypto_kem_keypair` and they are the same. The third line is the ciphertext generated by `crypto_kem_enc`. The ciphertext is very similar, but it's not exactly the same, so clearly one of the implementations has a bug.

**Comment by alperbilgin** [comment]
Hi,

It somehow escaped my attention, sorry. I can reproduce this error for `kyber768-90s` and `kyber1024`. Indeed, the difference is in the public key not in the ciphertext. The first two lines are just random numbers. The faulty letters are **e617d0** and it is converted to a coefficient by using `poly_frombytes` function as **0xD01**, which is **3329** in decimal. The corresponding letters are **e60700**, which translated as **0x000** and **0** in decimal, for `clean` implementation. The coefficient before barrett reduction is actually **-3329** if you follow carefully. Therefore, it is not actually a bug but a strange situation that showed up after our new stack optimization in `indcpa_keypair` function. After all, I added a redundant barrett reduction to turn 3329 to 0 again.

**Comment by Ko-** [comment]
If that extra barrett reduction really is redundant then maybe it's the other implementations that need to change. @mkannwischer do you have an opinion about this?

I just went ahead and re-ran the benchmarks. It's slightly slower but very similar compared to what you reported in the paper, presumably indeed because of our lack of `-flto` and the now added barret reduction.

**Comment by cryptojedi** [comment]
Ko- <notifications@github.com> wrote:

> If that extra barrett reduction really is redundant then maybe it's
> the other implementations that need to change. @mkannwischer do you
> have an opinion about this?

My understanding is that this reduction is required to ensure that all
output coefficients are in [0, q-1]. If this is the case, then it's not
redundant (but could maybe be replaced by a slightly cheaper
constant-time conditional addition).

**Comment by alperbilgin** [comment]
Maybe redundant is the wrong choice of word here. What I meant was the algorithm works correctly without it as well. However, the purpose here is to have the same KAT values for all implementations. 

> My understanding is that this reduction is required to ensure that all output coefficients are in [0, q-1]. If this is the case, then it's not redundant (but could maybe be replaced by a slightly cheaper constant-time conditional addition).

Yes, this is the case. The output coefficients should be in [0, q-1] to ensure that there is a single output value for each possible KAT inputs. However, `barrett_reduce` function returns an output in [0, q]. This was the reason for getting different test vectors before. The same situation might also happen for the secret key so I moved `poly_reduce` to `poly_tobytes`, which is called to serialize both secret and public keys. As said before, a constant-time conditional subtraction may also be used to reduce q to 0 but there is already a fast assembly implementation of the Barrett reduction.

**Comment by Ko-** [comment]
Sorry for the small delay, but it's merged now. Thanks again for helping integrating your work into `pqm4`!

**Pull request merged**
