### PR TITLE
Improved Plantard Arithmetic for Lattice-based Cryptography

### PR DESCRIPTION
**Pull request by JunhaoHuang**
This PR integrates the improved Plantard arithmetic presented in [Improved Plantard Arithmetic for Lattice-based Cryptography](https://tches.iacr.org/index.php/TCHES/article/view/9833) into Kyber. The source codes can also be found at https://github.com/UIC-ESLAS/ImprovedPlantardArithmetic. 

The new implementation locates in the crypto_kem/kyber**/m4plantard folder. Note that there is a small speed difference between this commit and the numbers in the paper due to the link-time optimization ('-flto'). pqm4 does not enable link-time optimizations while all codes described in [Improved Plantard Arithmetic for Lattice-based Cryptography](https://tches.iacr.org/index.php/TCHES/article/view/9833) enable it.

### CODE REVIEW

**Comment by mkannwischer** [comment]
Thanks @JunhaoHuang!
Is there any reason to keep the m4fspeed implementations? I guess those should also be using Plantard mul?

**Comment by JunhaoHuang** [comment]
@mkannwischer The m4fspeed implementations contain a better matrix-vector multiplication at the cost of larger stack usage. We did not integrate the Plantard multiplication into the m4fspeed version due to the limited time. But I think future work can be done to integrate the Plantard multiplication into the m4fspeed implementations.

**Comment by mkannwischer** [comment]
I don't think that is too much work. Let me see if I can do that before we merge it. 
Otherwise, this is going to be very confusing.

**Comment by JunhaoHuang** [comment]
I can also help with it this week.

**Comment by JunhaoHuang** [comment]
Dear Matthias @mkannwischer 

I have integrated the Plantard mul into the m4fspeed version. I also rename the previous m4plantard directory into the m4fstack. Would you please check if there are any issues? Thanks!
Cheers,
Junhao

**Comment by vincentvbh** [comment]
Hi, @JunhaoHuang. Nice to see improvements on NTTs. I think you need a reduction at the end of ntt-fast to get the right testvectors.

**Comment by mkannwischer** [comment]
@JunhaoHuang, Thank you very much for integrating this!
I ran the tests and testvectors, and it works fine for me. I'll run the benchmarks and then get this merged asap. 
@vincentvbh, for which parameter set did you get an error?

**Comment by vincentvbh** [comment]
Never mind. I made a mistake.

**Comment by JunhaoHuang** [comment]
Thank you @mkannwischer @vincentvbh for reviewing our implementation!

@vincentvbh The coefficients generated from ntt_fast are smaller than 3.5q. I checked all the codes that use these coefficients, either the matrix-vector multiplication or the inner-product operation. I think these coefficients can be directly used in the better accumulation technique and it would not overflow the 32-bit signed integer too ($3.5kq^2\leq 14q^2<2^{28}$).

**Comment by mkannwischer** [comment]
I finished the benchmarks. Thanks again @JunhaoHuang!

**Pull request merged**
