### PR TITLE
Reduce saber's stack usage

### PR DESCRIPTION
**Pull request by jowlo**
Some time ago, @pyropeter and I took a rather quick look at the `saber/ref` implementation to reduce its stack usage.

By simply avoiding unnecessary copies, reordering some lines (without any effects on the scheme itself) and reusing large arrays, we were able to reduce `saber`'s stack usage by quite a lot. I do not have the numbers anymore and unfortunately do not have a `stm32f4` board available atm to rerun the benchmarks. However, it should be quite obvious from the code changes that a lot less arrays are allocated on the stack. 
The changes, however, reduce code readability at a few places.

I am not sure if it is appropriate to merge this into the _reference_ implementation, but I thought, we could at least share this. Your comments are welcome.

### CODE REVIEW

**Comment by mkannwischer** [comment]
Thanks for your pull request. I'll run the benchmarks in a bit and share it here.

I think that ref implementations should be as close as possible to the ref implementation submitted to NIST, i.e. I'm not in favor of merging it here. If the improvement is significant, the way to go would be to create an opt implementation (see README)

There is also an M4 optimised SABER (https://eprint.iacr.org/2018/682) which was recently accepted to CHES 2018 - maybe someone could merge that as well (preferably the authors). Code is at https://github.com/KULeuven-COSIC/SABER

**Comment by mkannwischer** [comment]
Here are the numbers: 

| scheme | implementation | key generation [cycles] | encapsulation [cycles] | decapsulation [cycles] |
| ------ | -------------- | ----------------------- | ---------------------- | -----------------------|
| saber (10 executions) | ref | AVG: 7,122,641 <br /> MIN: 7,122,641 <br /> MAX: 7,122,641 |  AVG: 9,470,597 <br /> MIN: 9,470,597 <br /> MAX: 9,470,597 | AVG: 12,303,737 <br /> MIN: 12,303,737 <br /> MAX: 12,303,737 |

changes to 

| scheme | implementation | key generation [cycles] | encapsulation [cycles] | decapsulation [cycles] |
| ------ | -------------- | ----------------------- | ---------------------- | -----------------------|
| saber (10 executions) | ref | AVG: 7,122,641 <br /> MIN: 7,122,641 <br /> MAX: 7,122,641 |  AVG: 9,469,556 <br /> MIN: 9,469,556 <br /> MAX: 9,469,556 | AVG: 11,566,293 <br /> MIN: 11,566,293 <br /> MAX: 11,566,293 |

and

| scheme | implementation | key generation [bytes] | encapsulation [bytes] | decapsulation [bytes] |
| ------ | -------------- | ----------------------- | ---------------------- | -----------------------|
| saber | ref | 12,616 |  14,888 | 15,984 |

changes to 

| scheme | implementation | key generation [bytes] | encapsulation [bytes] | decapsulation [bytes] |
| ------ | -------------- | ----------------------- | ---------------------- | -----------------------|
| saber | ref | 12,616 |  13,192 | 14,288 |

Are these roughly the numbers you had as well @jowlo?

**Comment by jowlo** [comment]
Thanks a lot fur running the benchmark! I actually remembered it to be even more effective, but the numbers look sensible and i guess, saving around 10% is not that bad after all for some high level code changes.

However, I agree that the reference implementation should resemble the NIST submission as close as possible. But calling this an `opt` implementation would be exaggerating...

So, it is okay with me if you close this PR - especially, since there are *really* optimized implementations waiting to be integrated...

**Comment by mkannwischer** [comment]
Thanks anyway.
Maybe it's still interesting for @Angshumank, @josebmera, and @FreVercauteren.

**Comment by Angshumank** [comment]
Hi @jowlo and @mkannwischer ,
Somhow, we missed the discussion earlier. 
Just for clarification, we know that there are indeed some repeated usages of arrays. The NIST code was written in a very easy to understand way. The optimized implementation was focused on optimizing the multiplication only.
In the recent paper, we have tried to reuse arrays as much as possible. We will integrate that code here very soon. We would be very grateful if you can look up the code and find ways to reduce stack usage eevn more.

**Pull request closed without merging**
